import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { ReactElement, Suspense } from 'react';
import Loading from './loading';
import Link from 'next/link';
import { ToastContainer } from 'react-toastify';
import "./page.scss";
import "../app/components/input-search/input-search.component.scss";
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout(props: {
    children: React.ReactNode;
    addremove: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ToastContainer />

                {/* <Suspense fallback={<p>Loading</p>}> */}
                {props.children}
                {props.addremove}
                {/* </Suspense> */}
            </body>
        </html>
    );
}
